name: Task
description: Miscellaneous work or changes
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the task is.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the specific requirements that must be met for this task to be considered Done.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: false
  - type: upload
    id: attachments
    attributes:
      label: Attachments
      description: Relevant files to attach.
    validations:
      required: false
